spring.application.name=pessoaSwagger

## H2 Database Properties
spring.datasource.url=jdbc:h2:mem:pessoadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

## H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

## Hibernate / JPA Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
